### ISSUE TITLE
Authentication failing for server with SmbServerNameHardeningLevel as 2

### ISSUE THREAD

**Issue by manutripathi82** [hierynomus/smbj#606]
Hi,
I am trying to connect with a SMB server which has hardening level as 2. Getting below error.
Exception in thread "main" com.hierynomus.mssmb2.SMBApiException: STATUS_ACCESS_DENIED (0xc0000022): Authentication failed for 'uname' using com.hierynomus.smbj.auth.NtlmAuthenticator@36902638
	at com.hierynomus.smbj.connection.SMBSessionBuilder.setupSession(SMBSessionBuilder.java:144)
	at com.hierynomus.smbj.connection.SMBSessionBuilder.setupSession(SMBSessionBuilder.java:142)
	at com.hierynomus.smbj.connection.SMBSessionBuilder.establish(SMBSessionBuilder.java:109)
	at com.hierynomus.smbj.connection.Connection.authenticate(Connection.java:192)

Code snippet

```
SMB2Dialect[] array = { SMB2Dialect.SMB_2XX, SMB2Dialect.SMB_2_0_2, SMB2Dialect.SMB_2_1, SMB2Dialect.SMB_3_0 };
SmbConfig config = SmbConfig.builder().withSigningRequired(true).withMultiProtocolNegotiate(true).withDfsEnabled(true).withEncryptData(true).withDialects(array).build();
		SMBClient client = new SMBClient(config);

		try (Connection connection = client.connect("xxxx.xxx.com")) {
			AuthenticationContext ac = new AuthenticationContext("uname", "pass".toCharArray(), "myDomain");
			Session session = connection.authenticate(ac);

			try (DiskShare share = (DiskShare) session.connectShare("rootFolder")) {
				for (FileIdBothDirectoryInformation f : share.list("", "*")) {
					System.out.println("File : " + f.getFileName());
				}
			}
		} finally {
			client.close();
		}
```

(I am able to connect using Windows client and also with Jcifs-ng library).
```
Here is the output for 'Get-SmbServerConfiguration'

AnnounceComment                 :
AnnounceServer                  : False
AsynchronousCredits             : 512
AuditSmb1Access                 : True
AutoDisconnectTimeout           : 15
AutoShareServer                 : True
AutoShareWorkstation            : True
CachedOpenLimit                 : 0
DurableHandleV2TimeoutInSeconds : 180
EnableAuthenticateUserSharing   : False
EnableDownlevelTimewarp         : False
EnableForcedLogoff              : True
EnableLeasing                   : True
EnableMultiChannel              : True
EnableOplocks                   : True
EnableSecuritySignature         : True
EnableSMB1Protocol              : True
EnableSMB2Protocol              : True
EnableStrictNameChecking        : True
EncryptData                     : False
IrpStackSize                    : 15
KeepAliveTime                   : 2
MaxChannelPerSession            : 32
MaxMpxCount                     : 50
MaxSessionPerConnection         : 16384
MaxThreadsPerQueue              : 20
MaxWorkItems                    : 1
NullSessionPipes                :
NullSessionShares               :
OplockBreakWait                 : 35
PendingClientTimeoutInSeconds   : 120
RejectUnencryptedAccess         : True
RequireSecuritySignature        : True
ServerHidden                    : True
Smb2CreditsMax                  : 8192
Smb2CreditsMin                  : 512
SmbServerNameHardeningLevel     : 2
TreatHostAsStableStorage        : False
ValidateAliasNotCircular        : True
ValidateShareScope              : True
ValidateShareScopeNotAliased    : True
ValidateTargetName              : True
```
I have tried using various SMbConfig options like withDFS, withMulti..., but none of this works.
Tried the maven (0.10.0) and also build the latest smbj 'master' branch, but same issue.

Here's the complete logs

```
[DEBUG] 2021-01-27 20:43:58.192 [main] ProxySocketFactory - Connecting to xxxx.xxx.com/zz.zz.zz.zz:445
[DEBUG] 2021-01-27 20:43:58.631 [main] DirectTcpPacketReader - Starting PacketReader on thread: Packet Reader for xxxx.xxx.com
[DEBUG] 2021-01-27 20:43:58.635 [main] SMBProtocolNegotiator - Negotiating dialects [SMB_2_0_2, SMB_2_1, SMB_2XX, SMB_3_0]
[DEBUG] 2021-01-27 20:43:58.636 [main] Connection - Granted 1 (out of 1) credits to SMB2_NEGOTIATE with message id << 0 >>
[DEBUG] 2021-01-27 20:43:58.639 [main] DirectTcpTransport - Writing packet SMB2_NEGOTIATE with message id << 0 >>
[DEBUG] 2021-01-27 20:43:58.642 [main] Promise - Awaiting << 0 >>
[DEBUG] 2021-01-27 20:43:59.079 [Packet Reader for xxxx.xxx.com] DirectTcpPacketReader - Received packet SMB2_NEGOTIATE with message id << 0 >>
[DEBUG] 2021-01-27 20:43:59.082 [Packet Reader for xxxx.xxx.com] SMB2CreditGrantingPacketHandler - Server granted us 1 credits for SMB2_NEGOTIATE with message id << 0 >>, now available: 1 credits
[DEBUG] 2021-01-27 20:43:59.089 [Packet Reader for xxxx.xxx.com] Promise - Setting << 0 >> to `SMB2_NEGOTIATE with message id << 0 >>`
[DEBUG] 2021-01-27 20:43:59.092 [main] SMBProtocolNegotiator - Negotiated the following connection settings: ConnectionContext{
  serverGuid=eb24a368-xxxx-4d1e-cccc-5d0938279c0d,
  serverName='xxxx.xxx.com',
  negotiatedProtocol=NegotiatedProtocol{dialect=SMB_3_0, maxTransactSize=8388608, maxReadSize=8388608, maxWriteSize=8388608},
  clientGuid=07c15920-ce7f-4fc6-8157-1e43f67bd5e5,
  clientCapabilities=[SMB2_GLOBAL_CAP_DFS, SMB2_GLOBAL_CAP_LARGE_MTU, SMB2_GLOBAL_CAP_ENCRYPTION],
  serverCapabilities=[SMB2_GLOBAL_CAP_DFS, SMB2_GLOBAL_CAP_LEASING, SMB2_GLOBAL_CAP_LARGE_MTU, SMB2_GLOBAL_CAP_ENCRYPTION],
  clientSecurityMode=2,
  serverSecurityMode=3,
  server='com.hierynomus.smbj.server.Server@1cbbffcd'
}
[INFO ] 2021-01-27 20:43:59.093 [main] PacketEncryptor - Initialized PacketEncryptor with Cipher << AES_128_CCM >>
[INFO ] 2021-01-27 20:43:59.093 [main] Connection - Successfully connected to: xxxx.xxx.com
[DEBUG] 2021-01-27 20:43:59.110 [main] NtlmAuthenticator - Initialized Authentication of uname using NTLM
[DEBUG] 2021-01-27 20:43:59.115 [main] Connection - Granted 1 (out of 1) credits to SMB2_SESSION_SETUP with message id << 1 >>
[DEBUG] 2021-01-27 20:43:59.115 [main] DirectTcpTransport - Writing packet SMB2_SESSION_SETUP with message id << 1 >>
[DEBUG] 2021-01-27 20:43:59.115 [main] Promise - Awaiting << 1 >>
[DEBUG] 2021-01-27 20:43:59.550 [Packet Reader for xxxx.xxx.com] DirectTcpPacketReader - Received packet SMB2_SESSION_SETUP with message id << 1 >>
[DEBUG] 2021-01-27 20:43:59.551 [Packet Reader for xxxx.xxx.com] SMB2CreditGrantingPacketHandler - Server granted us 1 credits for SMB2_SESSION_SETUP with message id << 1 >>, now available: 1 credits
[DEBUG] 2021-01-27 20:43:59.551 [Packet Reader for xxxx.xxx.com] Promise - Setting << 1 >> to `SMB2_SESSION_SETUP with message id << 1 >>`
[DEBUG] 2021-01-27 20:43:59.551 [main] SMBSessionBuilder - More processing required for authentication of uname using com.hierynomus.smbj.auth.NtlmAuthenticator@36902638
[DEBUG] 2021-01-27 20:43:59.552 [main] NtlmAuthenticator - Received token: <I have removed the token to hide details of customer's system>
[DEBUG] 2021-01-27 20:43:59.554 [main] ASN1InputStream - Read ASN.1 object: ASN1TaggedObject[ASN1Tag[CONTEXT_SPECIFIC,CONSTRUCTED,1],<unknown>]
[DEBUG] 2021-01-27 20:43:59.555 [main] ASN1InputStream - Read ASN.1 object: ASN1TaggedObject[ASN1Tag[CONTEXT_SPECIFIC,CONSTRUCTED,0],<unknown>]
[DEBUG] 2021-01-27 20:43:59.556 [main] ASN1InputStream - Read ASN.1 object: ASN1TaggedObject[ASN1Tag[CONTEXT_SPECIFIC,CONSTRUCTED,1],<unknown>]
[DEBUG] 2021-01-27 20:43:59.556 [main] ASN1InputStream - Read ASN.1 object: ASN1TaggedObject[ASN1Tag[CONTEXT_SPECIFIC,CONSTRUCTED,2],<unknown>]
[DEBUG] 2021-01-27 20:43:59.556 [main] ASN1InputStream - Read ASN.1 object: ASN1Sequence[[ASN1TaggedObject[ASN1Tag[CONTEXT_SPECIFIC,CONSTRUCTED,0],<unknown>], ASN1TaggedObject[ASN1Tag[CONTEXT_SPECIFIC,CONSTRUCTED,1],<unknown>], ASN1TaggedObject[ASN1Tag[CONTEXT_SPECIFIC,CONSTRUCTED,2],<unknown>]]]
[DEBUG] 2021-01-27 20:43:59.556 [main] ASN1InputStream - Read ASN.1 object: ASN1Enumerated[1]
[DEBUG] 2021-01-27 20:43:59.557 [main] ASN1InputStream - Read ASN.1 object: ASN1ObjectIdentifier[1.3.6.1.4.1.311.2.2.10]
[DEBUG] 2021-01-27 20:43:59.557 [main] ASN1InputStream - Read ASN.1 object: ASN1OctetString[[Removed some data from here, 0, 1, 0, 16, 0, 68, 0, 67, 0, 83, 0, 69, 0, 82, 0, 86, 0, 69, 0, 82, 0, 4, 0, 20, 0, 110, 0, 100, 0, 108, 0, 112, 0, 113, 0, 97, 0, 46, 0, 99, 0, 111, 0, 109, 0, 3, 0, 38, 0, 100, 0, 99, 0, 115, 0, 101, 0, 114, 0, 118, 0, 101, 0, 114, 0, 46, 0, 110, 0, 100, 0, 108, 0, 112, 0, 113,, 0, 109, 0, 5, 0, 20, 0, 110, 0, 100, 0, 108, 0, 112, 0, 113, 0, 97, 0, 46, 0, 99, 0, 111, 0, 109, 0, 7, 0, 8, 0, 27, -87, -59, 38, -65, -12, -42, 1, 0, 0, 0, 0]]
[DEBUG] 2021-01-27 20:43:59.558 [main] NtlmChallenge - Windows version = WindowsVersion[WINDOWS_MAJOR_VERSION_10, WINDOWS_MINOR_VERSION_0, 14393, NTLMSSP_REVISION_W2K3]
[DEBUG] 2021-01-27 20:43:59.559 [main] NtlmAuthenticator - Received NTLM challenge from: myDomain
[DEBUG] 2021-01-27 20:44:00.168 [main] Connection - Granted 1 (out of 1) credits to SMB2_SESSION_SETUP with message id << 2 >>
[DEBUG] 2021-01-27 20:44:00.169 [main] DirectTcpTransport - Writing packet SMB2_SESSION_SETUP with message id << 2 >>
[DEBUG] 2021-01-27 20:44:00.169 [main] Promise - Awaiting << 2 >>
[DEBUG] 2021-01-27 20:44:00.603 [Packet Reader for xxxx.xxx.com] DirectTcpPacketReader - Received packet SMB2_SESSION_SETUP with message id << 2 >>
[DEBUG] 2021-01-27 20:44:00.604 [Packet Reader for xxxx.xxx.com] SMB2CreditGrantingPacketHandler - Server granted us 1 credits for SMB2_SESSION_SETUP with message id << 2 >>, now available: 1 credits
[DEBUG] 2021-01-27 20:44:00.604 [Packet Reader for xxxx.xxx.com] Promise - Setting << 2 >> to `SMB2_SESSION_SETUP with message id << 2 >>`
[DEBUG] 2021-01-27 20:44:00.605 [main] DirectTcpPacketReader - Stopping PacketReader...
[INFO ] 2021-01-27 20:44:00.605 [main] Connection - Closed connection to xxxx.xxx.com
[INFO ] 2021-01-27 20:44:00.606 [Packet Reader for xxxx.xxx.com] DirectTcpPacketReader - Thread[Packet Reader for xxxx.xxx.com,5,main] stopped.
[DEBUG] 2021-01-27 20:44:00.608 [main] SMBClient - Connection to << xxxx.xxx.com:445 >> closed
[INFO ] 2021-01-27 20:44:00.608 [main] SMBClient - Going to close all remaining connections
```

Please let me know what can be the issue here ?

**Comment by manutripathi82** [comment]
@hierynomus can you please provide some insight on this issue.

**Comment by hierynomus** [comment]
What does the server side say that the problem is? Or can you get a pcap of both smbj connecting and jcifs-ng connecting? Then I can figure out what the difference is.

**Comment by manutripathi82** [comment]
Sorry but I do not have access to server logs. The only difference we find is that if we server makes SmbServerNameHardeningLevel as 0, it works.

I am attaching the pcaps for both cifs and smbj scenario.
[pcaps.zip](https://github.com/hierynomus/smbj/files/5897336/pcaps.zip)

**Comment by chrisgch** [comment]
I can reproduce this error with Windows 10 pro as the server by starting Powershell.exe and executing the following command:
Set-SmbServerConfiguration -SmbServerNameHardeningLevel 2

Here is the data from the event log- Applications and Services Logs - Microsoft - Windows - SMBServer:
[EventLog.txt](https://github.com/hierynomus/smbj/files/5919402/EventLog.txt)

**Comment by manutripathi82** [comment]
@hierynomus did you happen to get a chance to look at the pcaps ?

**Comment by hierynomus** [comment]
Yes, I did, and I was trying to fix some stuff, as I saw that the MIC (message integrity code) wasn't added for the right condition in smbj. So am working on it.

Do you have any idea how to simulate the SmbServerNameHardeningLevel in Samba? The integration tests use Samba on a linux docker image.

**Comment by manutripathi82** [comment]
Sorry, I do not know how to simulate that. I haven't worked on the server side of it :(

**Comment by manutripathi82** [comment]
@hierynomus any update on this ?

**Comment by manutripathi82** [comment]
@hierynomus did you get a chance to look into this. I am stuck at it.

**Comment by hierynomus** [comment]
@manutripathi82 I've submitted a PR which I hope should fix the issue. Can you take a look?

**Comment by manutripathi82** [comment]
@hierynomus thanks for looking into this. I'll give it a try. Do I need to add some tweaks in the application code or just the usual code as mentioned on your github page (Example - A - Listing Files on a Share/Folder) would suffice ?

**Comment by hierynomus** [comment]
Interfaces haven't been changed, so your code should work as is if you use
the pr.

Op za 15 mei 2021 08:27 schreef MANU TRIPATHI ***@***.***>:

**Comment by manutripathi82** [comment]
@hierynomus I tried the simple file listing code but still the same error. Attached is the zip file containing the new trace smbj-606.pcapng (zip also has the older traces for your reference).
[pcaps.zip](https://github.com/hierynomus/smbj/files/6483941/pcaps.zip)

**Comment by hierynomus** [comment]
@manutripathi82 Ok, found another discrepancy in the NTLM authentication, can you test it using the new code from the PR?

**Comment by manutripathi82** [comment]
@hierynomus I tried the new PR also. Same error. Attached are the pcap and debug logs.
I did try to debug and could see that the code flows through the segment where the client target info sets the MsvAvTargetName  as cifs/.. but in the final authenticate trace it is missing.

I am no expert of your code but what I suspect is that instead of setting serverNtlmChallenge.getTargetInfo() it should be clientTargetInfo in the below code (since you already made copy of server info into client info). 
```
byte[] ntlmv2ClientChallenge = ntlmFunctions.getNTLMv2ClientChallenge(serverNtlmChallenge.getTargetInfo());
```
[logs.zip](https://github.com/hierynomus/smbj/files/6498260/logs.zip)

**Comment by hierynomus** [comment]
Yes, you're right! I extracted the TargetInfo to do just that, butg something happened in between and I forgot to fix that line.
It's now pushed, can you try again?

**Comment by manutripathi82** [comment]
@hierynomus thanks a lot, it works now but only if I set the SMbConfig with a security provider 
```
.withSecurityProvider(new BCSecurityProvider()).build();
```

Without using a SmbConfig i.e. the vanilla code, I get below error on console

Exception in thread "main" java.lang.UnsupportedOperationException
	at com.hierynomus.security.jce.JceSecurityProvider.getDerivationFunction(JceSecurityProvider.java:64)
	at com.hierynomus.smbj.connection.SMBSessionBuilder.deriveKey(SMBSessionBuilder.java:291)
	at com.hierynomus.smbj.connection.SMBSessionBuilder.setupSession(SMBSessionBuilder.java:168)
	at com.hierynomus.smbj.connection.SMBSessionBuilder.setupSession(SMBSessionBuilder.java:142)
	at com.hierynomus.smbj.connection.SMBSessionBuilder.establish(SMBSessionBuilder.java:109)
	at com.hierynomus.smbj.connection.Connection.authenticate(Connection.java:192)
	at FilesLister.tryBasic(FilesLister.java:103)
	at FilesLister.main(FilesLister.java:55)

Seems more like my setup problem. Although I have JCE extended security libs set in jre

**Comment by hierynomus** [comment]
Wow, great to hear it works. I'll merge the PR.

As for the `UnsupportedOperationException`, this is to be expected. The JCE security provider currently does not support the Key Derivation Functions needed for SMB3 support. This is only supported by the Bouncy Castle Provider. I'll make sure to document that.
